### PR TITLE
Added container command parameter

### PR DESCRIPTION
**Pull request by Matty666**
This enables passing commands to containers when they are started.
This implements issue #53

### CODE REVIEW

**Comment by nicjo814** [comment]
This looks like are very nice addition to the plug-in. I'll give it a try later today to see how it works. Thanks for the contribution!

**Comment by Matty666** [comment]
@subzero79 I can change those columns to be hidden by default, no problem, is there an example of the properties I need to set somewhere?

**Comment by subzero79** [comment]
From memory now, the filesystem grid in core Omv has some hidden columns

just double check:

hidden: true

**Comment by subzero79** [comment]
Gonna merge this. The release of 4.x is very close. I have to make a new PR for the new changes.

**Comment by Matty666** [comment]
Ok no problem. I checked and you're right, just haven't had time to change and test it. I'll submit a new pr with the change.




Matt
________________________________

**Comment by subzero79** [comment]
I mean i have to submit a big PR from my repository. Big changes, look at my github unixsocket branch

**Pull request merged**
