### PR TITLE
Logofix

### PR DESCRIPTION
**Pull request by nicjo814**
This should fix the issue when an image in the Repo tab uses a logo that isn't available. The solution is to simply skip such images.

### CODE REVIEW

**Comment by ryecoaaron** [comment]
The changelig stuff is fine. Just is white space removed from end of lines

**Comment by subzero79** [comment]
How do we test this @nicjo814 ?

send to localhost the image URL in /etc/hosts?

**Comment by nicjo814** [comment]
That sounds like a nice way. I tested it when there was an actual broken URL in the real json data...

**Comment by subzero79** [comment]
I've tried this both URL in /etc/hosts 

https://tools.linuxserver.io/docker-templates.json

http://openmediavault-plugin-developers.github.io/openmediavault-docker-repo/dockerlist_amd64.xml

And i cannot reproduce the error, so it must fail for single image

**Pull request merged**
