### PR TITLE
Adding module for Services indication

### PR DESCRIPTION
**Pull request by 1activegeek**
First attempt at contributing code! Hopefully this looks good. Copied from what other were doing, and had to iron out that this plugin has the config property listed as "enabled" vs "enable" which most others are using.

### CODE REVIEW

**Comment by subzero79** [comment]
Looks good to me. I tested and works as expected

**Comment by 1activegeek** [comment]
Sweet! Glad to be contributing for once. I was concerned as I read the HOWTO on plugin development which outlined a different method it seems to likely get the same information. In the end, I worked with a copy from one of the plugins instead of trying to decipher the howto guided method. Glad it worked!

**Comment by subzero79** [comment]
@nicjo814 any comments? is the listener necessary ?

**Comment by nicjo814** [comment]
The code looks good to me. I don't know about the listener though, haven't worked with those before. I thought it was used to detect changes to settings etc and then fire some script after you hit "apply".

**Pull request merged**
